name: Sync labels

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [main]
    paths: [.github/workflows/sync-labels.yml]
  workflow_dispatch:

jobs:
  run:
    uses: Friedinger/Configs/.github/workflows/action-sync-labels.yml@d785a0be35c0beb0ab714751f0e32e2878e5c5c0 # main
    permissions:
      issues: write
