name: Sync webhook

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [main]
    paths: [.github/workflows/sync-webhook.yml]
  workflow_dispatch:

jobs:
  run:
    uses: Friedinger/configs/.github/workflows/action-sync-webhook.yml@main
    secrets:
      WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
